### ISSUE TITLE
Updates for compiling against OSG 3.3.7

### ISSUE THREAD

**Issue by crubel** [mccdo/osgworks#51]
Hello,

I have patched the current version of osgWorks so that it will compile against OSG 3.3.7.  Ho do I go submitting the patches to see if we can get them applied? 

Summary diff:

<code>
    # Date 1430842722 14400
    # Node ID 6725c7815b686f002712a87147cd5e1c847cdc24
    # Parent  2fdfb980ed485e45d407cd9022dbc7a668ec3bf7
    updates for newer OSG versions 3.3.3 and newer  CGR

    diff --git a/osgWorks_3_00_00/include/osgwTools/FBOUtils.h b/osgWorks_3_00_00/include/osgwTools/FBOUtils.h
--- a/osgWorks_3_00_00/include/osgwTools/FBOUtils.h
+++ b/osgWorks_3_00_00/include/osgwTools/FBOUtils.h
@@ -21,7 +21,7 @@
 #ifndef __OSGWTOOLS_FBO_UTILS_H__
 #define __OSGWTOOLS_FBO_UTILS_H__ 1
 
-
+#include <osg/Version>
 #include "osgwTools/Export.h"
 #include <osg/FrameBufferObject>
 
@@ -92,7 +92,17 @@
 
 
 
+#if OSG_MIN_VERSION_REQUIRED( 3,3,3 )
 
+GLvoid OSGWTOOLS_EXPORT glGenFramebuffers( osg::GLExtensions* fboExt, GLsizei n, GLuint* framebuffer );
+GLvoid OSGWTOOLS_EXPORT glDeleteFramebuffers( osg::GLExtensions* fboExt, GLsizei n, GLuint* framebuffer );
+GLvoid OSGWTOOLS_EXPORT glBindFramebuffer( osg::GLExtensions* fboExt, GLenum target, GLuint framebuffer );
+
+GLvoid OSGWTOOLS_EXPORT glFramebufferTexture2D( osg::GLExtensions* fboExt, GLenum target, GLenum attachment,
+            GLenum textarget, GLuint texture, GLint level );
+GLvoid OSGWTOOLS_EXPORT glBlitFramebuffer(  osg::GLExtensions* fboExt, GLint srcX0, GLint srcY0, GLint srcX1,
+            GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter );
+#else
 GLvoid OSGWTOOLS_EXPORT glGenFramebuffers( osg::FBOExtensions* fboExt, GLsizei n, GLuint* framebuffer );
 GLvoid OSGWTOOLS_EXPORT glDeleteFramebuffers( osg::FBOExtensions* fboExt, GLsizei n, GLuint* framebuffer );
 GLvoid OSGWTOOLS_EXPORT glBindFramebuffer( osg::FBOExtensions* fboExt, GLenum target, GLuint framebuffer );
@@ -102,6 +112,7 @@
 GLvoid OSGWTOOLS_EXPORT glBlitFramebuffer(  osg::FBOExtensions* fboExt, GLint srcX0, GLint srcY0, GLint srcX1,
             GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter );
 
+#endif
 
 /*@}*/
 
diff --git a/osgWorks_3_00_00/src/osgwQuery/QueryUtils.cpp b/osgWorks_3_00_00/src/osgwQuery/QueryUtils.cpp
--- a/osgWorks_3_00_00/src/osgwQuery/QueryUtils.cpp
+++ b/osgWorks_3_00_00/src/osgwQuery/QueryUtils.cpp
@@ -191,7 +191,12 @@
     osg::NodePath::reverse_iterator rit;
     for( rit=np.rbegin(); rit!=np.rend(); rit++ )
     {
+
+#if OSG_MIN_VERSION_REQUIRED( 3,3,3 )
+        osg::Callback* cb = (*rit)->getCullCallback();
+#else
         osg::NodeCallback* cb = (*rit)->getCullCallback();
+#endif
         QueryCullCallback* qcc = dynamic_cast< QueryCullCallback* >( cb );
 
         osgwQuery::QueryComputation* nd( NULL );
@@ -221,7 +226,11 @@
 
 void RemoveQueries::apply( osg::Node& node )
 {
+#if OSG_MIN_VERSION_REQUIRED( 3,3,3 )
+    osg::Callback* cb = node.getCullCallback();
+#else
     osg::NodeCallback* cb = node.getCullCallback();
+#endif
     QueryCullCallback* qcc = dynamic_cast< QueryCullCallback* >( cb );
 
     if( qcc != NULL )
diff --git a/osgWorks_3_00_00/src/osgwTools/FBOUtils.cpp b/osgWorks_3_00_00/src/osgwTools/FBOUtils.cpp
--- a/osgWorks_3_00_00/src/osgwTools/FBOUtils.cpp
+++ b/osgWorks_3_00_00/src/osgwTools/FBOUtils.cpp
@@ -29,8 +29,11 @@
 
 #define OSG_FBO_CHANGE_VERSION 20906
 
-
+#if OSG_MIN_VERSION_REQUIRED( 3,3,3 )
+GLvoid glGenFramebuffers( osg::GLExtensions* fboExt, GLsizei n, GLuint* framebuffer )
+#else
 GLvoid glGenFramebuffers( osg::FBOExtensions* fboExt, GLsizei n, GLuint* framebuffer )
+#endif
 {
 #if( OSGWORKS_OSG_VERSION >= OSG_FBO_CHANGE_VERSION )
     fboExt->glGenFramebuffers( n, framebuffer );
@@ -39,7 +42,11 @@
 #endif
 }
 
+#if OSG_MIN_VERSION_REQUIRED( 3,3,3 )
+GLvoid glDeleteFramebuffers( osg::GLExtensions* fboExt, GLsizei n, GLuint* framebuffer )
+#else
 GLvoid glDeleteFramebuffers( osg::FBOExtensions* fboExt, GLsizei n, GLuint* framebuffer )
+#endif
 {
 #if( OSGWORKS_OSG_VERSION >= OSG_FBO_CHANGE_VERSION )
     fboExt->glDeleteFramebuffers( n, framebuffer );
@@ -48,7 +55,11 @@
 #endif
 }
 
+#if OSG_MIN_VERSION_REQUIRED( 3,3,3 )
+GLvoid glBindFramebuffer( osg::GLExtensions* fboExt, GLenum target, GLuint framebuffer )
+#else
 GLvoid glBindFramebuffer( osg::FBOExtensions* fboExt, GLenum target, GLuint framebuffer )
+#endif
 {
 #if( OSGWORKS_OSG_VERSION >= OSG_FBO_CHANGE_VERSION )
     fboExt->glBindFramebuffer( target, framebuffer );
@@ -58,8 +69,13 @@
 }
 
 
+#if OSG_MIN_VERSION_REQUIRED( 3,3,3 )
+GLvoid glFramebufferTexture2D( osg::GLExtensions* fboExt, GLenum target, GLenum attachment,
+            GLenum textarget, GLuint texture, GLint level )
+#else
 GLvoid glFramebufferTexture2D( osg::FBOExtensions* fboExt, GLenum target, GLenum attachment,
             GLenum textarget, GLuint texture, GLint level )
+#endif
 {
 #if( OSGWORKS_OSG_VERSION >= OSG_FBO_CHANGE_VERSION )
     fboExt->glFramebufferTexture2D( target, attachment, textarget, texture, level );
@@ -68,8 +84,13 @@
 #endif
 }
 
+#if OSG_MIN_VERSION_REQUIRED( 3,3,3 )
+GLvoid glBlitFramebuffer( osg::GLExtensions* fboExt, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1,
+            GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter )
+#else
 GLvoid glBlitFramebuffer( osg::FBOExtensions* fboExt, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1,
             GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter )
+#endif
 {
 #if( OSGWORKS_OSG_VERSION >= OSG_FBO_CHANGE_VERSION )
     fboExt->glBlitFramebuffer( srcX0, srcY0, srcX1, srcY1,
</code>

Cheers,

Curtis

**Comment by crubel** [comment]
Probably a better way to do this from the output above, so just let me know what you want...

Cheers,

Curtis

**Comment by aquawicket** [comment]
Excellent I need this..  however not sure how to apply this patch. never done it before.

**Comment by crubel** [comment]
Here is a 7zip'd file of the entire osgWorks project that I patched for
OSG 3.3.7...

I make no claims about anything other than it compiles against OSG 3.3.7
now.  We only use a few functions out of this entire package, so cannot
guarantee anything..

Cheers,



On Saturday, May 9, 2015 04:57, "aquawicket" <notifications@github.com> said:

**Comment by XenonofArcticus** [comment]
I'll try to integrate your changes by next week. Thanks for the patch. Drop me a note sometime, Curtis, was wondering what you guys were up to.

**Comment by karlsvec** [comment]
@crubel You might consider forking the osgworks repo and applying your patch on a branch there. It would help streamline getting your changes merged.

**Comment by crubel** [comment]
OK I have forked the repo, added a new branch(OpenSceneGraph3_3_3_7_Patch) to the fork,
and committed the changes to my forked copy.

Not quiet sure what has to happen next....as GIT is a new thing for me..

Cheers,

Curtis 

On Friday, May 15, 2015 14:07, "Karl Svec" <notifications@github.com> said:

**Comment by XenonofArcticus** [comment]
You should now be able to generate a patch request. Then we can more or
less trivially accept that patch request.

**Comment by karlsvec** [comment]
@crubel Yes, submit a [pull request](https://help.github.com/articles/using-pull-requests/) for your branch, and that will make it very easy for @XenonofArcticus to review and merge your changes.

**Comment by crubel** [comment]
Ok I have submitted a pull request.  Hopefully I did this correctly as this is
my first time asking for this type of thing.  The request seems to show it can be easily
merged once approved if I am understanding the output I saw onscreen.

Cheers
Curtis

**Comment by XenonofArcticus** [comment]
Should be good. Thanks!
